import type { ProjectArtifact } from "../../types";

export const flightTrackerArtifacts: ProjectArtifact[] = [
  {
    slug: "prd",
    label: "PRODUCT DEFINITION",
    title: "Product Requirements Document",
    summary: "A product brief for the event-streaming prototype, including the proposed user, requirements, metrics, risks, and validation plan.",
    sections: [
      {
        title: "Context and source",
        state: "Current build",
        body: ["I created this portfolio PRD from the public repository at commit fc0ea6f after completing the initial prototype."],
        table: { headers: ["Field", "Value"], rows: [
          ["Version", "1.0"],
          ["Updated", "September 3, 2026"],
          ["Source commit", "fc0ea6ff4c267796fb2271a63443b3f53500ff76"],
          ["Evidence boundary", "Architecture and source behavior are inspectable; the user, workflow value, reliability, and product outcomes remain hypotheses"],
        ] },
      },
      {
        title: "Product brief",
        state: "Design target",
        body: ["Give a cargo operations coordinator one current view of selected cargo flights with clear freshness and connection status. The interface supports monitoring while operational systems retain authority."],
        table: { headers: ["PRD field", "Decision"], rows: [
          ["Status", "Public engineering prototype; frontend build reproduced; end-to-end and user validation pending"],
          ["Product owner", "Gokul Gopalakrishnan · independent end-to-end build"],
          ["Primary-user hypothesis", "Cargo operations coordinator monitoring active FedEx and UPS flights"],
          ["Target job", "Locate and inspect a cargo flight in a current shared view"],
          ["Hypothesized current workflow", "Refresh public flight sources or move among disconnected views with limited freshness information"],
          ["Current boundary", "Event ingestion and map visualization prototype for monitoring research"],
        ] },
      },
      {
        title: "Problem and open assumptions",
        state: "Design target",
        body: ["The repository implements the components of the flight-state path. An end-to-end run remains pending, along with user and operational validation."],
        table: { headers: ["Statement", "Evidence state", "Product implication"], rows: [
          ["OpenSky flight states can be filtered by FDX and UPS callsigns", "Implemented in producer.py", "A bounded cargo-flight stream exists"],
          ["A broker decouples ingestion from browser delivery", "Implemented architecture", "Source and presentation components can evolve independently"],
          ["Cargo coordinators need this view", "User hypothesis", "Validate the role, task, and required fields before expanding scope"],
          ["A shared current view reduces monitoring effort", "Value hypothesis", "Measure task behavior against the current workflow"],
        ] },
      },
      {
        title: "Outcome to validate",
        state: "Design target",
        table: { headers: ["Layer", "Desired change", "Proof required"], rows: [
          ["User outcome", "Find and inspect the flight relevant to the current task", "Task success and completion time in moderated sessions"],
          ["Trust outcome", "Know when the view is current, stale, disconnected, or using mock data", "Users correctly interpret state in failure scenarios"],
          ["System outcome", "Deliver consistent updates with visible loss and duplication checks", "Instrumented reliability run"],
          ["Business hypothesis", "Reduce effort required to maintain cargo-flight awareness", "Baseline comparison in a bounded pilot"],
        ] },
      },
      {
        title: "End-to-end monitoring journey",
        state: "Design target",
        table: { headers: ["Step", "User intent", "Product response", "Status"], rows: [
          ["1 · Open", "See whether the view is trustworthy", "Show source, connection, and last-update state", "Proposed"],
          ["2 · Find", "Locate a known cargo flight", "Search or filter by callsign and operator", "Proposed"],
          ["3 · Inspect", "Review current position and movement data", "Map marker and flight detail", "Marker popup implemented; operational detail proposed"],
          ["4 · Monitor", "Recognize new, updated, and stale records", "Stream updates and expire stale markers", "Streaming implemented; freshness behavior proposed"],
          ["5 · Recover", "Understand a source or connection failure", "Visible degraded state and reconnect path", "Proposed"],
        ] },
      },
      {
        title: "Release scope and non-goals",
        state: "Design target",
        table: { headers: ["Priority", "Scope", "Boundary"], rows: [
          ["Implemented", "Poll OpenSky, filter FDX/UPS, publish to Redpanda, forward over WebSocket, render Leaflet markers", "Operational workflow validation remains open"],
          ["P0", "Search, current/stale state, connection state, correct units, and deterministic mock mode", "Required before user evaluation"],
          ["P1", "Operator filters, flight detail, reconnect/backoff, and multi-client delivery", "Required before a bounded pilot"],
          ["Out of scope", "Dispatch authority, safety decisions, route optimization, alerts, historical analytics, or production SLA", "Current scope: monitoring prototype"],
        ] },
      },
      {
        title: "Requirements and acceptance criteria",
        state: "Design target",
        table: { headers: ["Type", "Requirement", "Acceptance criterion", "Status"], rows: [
          ["Data", "Represent flight identity and measurement units consistently", "The schema names units and rejects unusable coordinates", "Required"],
          ["Trust", "Expose source and freshness", "The interface distinguishes live, mock, stale, and disconnected states", "Required"],
          ["Task", "Find a specified cargo flight", "A user can search by callsign and open its detail directly", "Proposed"],
          ["Reliability", "Recover from connection loss", "The client reconnects with bounded backoff and exposes recovery state", "Proposed"],
          ["Distribution", "Serve the same current event to multiple viewers", "Concurrent clients receive equivalent updates through a broadcast path", "Proposed"],
          ["Fallback", "Demonstrate during an external API outage", "Mock data is clearly labeled and follows the same contract", "Partially implemented"],
        ] },
      },
      {
        title: "Success measures",
        state: "Proposed next step",
        table: { headers: ["Metric", "Baseline / target", "Method", "Decision"], rows: [
          ["Specified-flight task success", "Establish with five moderated sessions", "Give each participant a callsign to locate and inspect", "Is the workflow usable?"],
          ["Time to locate and inspect", "Compare with participant's current method", "Timed task with completion evidence", "Does the product reduce monitoring effort?"],
          ["Event-to-render latency p50/p95", "Target set after baseline run", "Timestamp producer, broker receipt, WebSocket send, and render", "Is update freshness acceptable?"],
          ["Lost or duplicate update rate", "Establish under deterministic test load", "Sequence-number reconciliation", "Can users trust the stream?"],
          ["Reconnect recovery time", "Establish after reconnect exists", "Controlled broker/backend/client interruption", "Does degraded service recover visibly?"],
          ["Stale-marker rate", "Establish after expiry policy exists", "Compare record age with displayed state", "Does the map hide uncertainty?"],
        ] },
      },
      {
        title: "Failure modes and safeguards",
        state: "Design target",
        table: { headers: ["Failure", "Current behavior", "Required product behavior"], rows: [
          ["OpenSky unavailable or rate-limited", "Producer logs and retries on the next poll", "Show degraded source state or switch to clearly labeled mock mode"],
          ["WebSocket disconnects", "Client logs disconnection; reconnect is planned", "Reconnect with backoff and visible status"],
          ["Old aircraft remains visible", "Expiry behavior is planned", "Mark stale, then remove according to a documented policy"],
          ["Multiple browsers connect", "Consumers share a group and may divide events", "Use one backend consumer with explicit fan-out"],
          ["Velocity displayed", "OpenSky meters/second is labeled kilometers/hour", "Normalize or label units correctly"],
          ["Live aircraft are outside the initial map view", "Map opens tightly around New York", "Fit view to current results or explain the bounded region"],
        ] },
      },
      {
        title: "Rollout plan",
        state: "Proposed next step",
        table: { headers: ["Stage", "Work", "Exit gate"], rows: [
          ["1 · Reproducible build", "Pin environment and run deterministic mock flow", "Documented event reaches the browser"],
          ["2 · Reliability harness", "Measure loss, duplication, latency, stale state, and reconnect behavior", "Known failure states are visible and bounded"],
          ["3 · Task prototype", "Add the minimum search, detail, and freshness workflow", "Core task passes internal acceptance"],
          ["4 · User evaluation", "Run five moderated cargo-monitoring tasks", "Problem, fields, and workflow are supported or revised"],
          ["5 · Limited pilot", "Observe a bounded non-operational workflow", "User value and reliability justify further investment"],
        ] },
      },
      {
        title: "Open questions",
        state: "Proposed next step",
        bullets: [
          "Which cargo-operations role owns the monitoring task, and what decision follows inspection?",
          "Which fields and freshness threshold make a flight state useful for an operating decision?",
          "Should the product follow individual flights, geographic regions, or operator fleets?",
          "What source terms, rate limits, and data-quality constraints apply to a real deployment?",
          "What existing workflow provides the baseline for time and effort?",
        ],
      },
    ],
  },
  {
    slug: "technical-design",
    label: "TECHNICAL JUDGMENT",
    title: "Event-Driven System Design",
    summary: "Maps the implemented flight-event path, data contract, known failure boundaries, architectural tradeoffs, and the changes required for a trustworthy multi-user product.",
    sections: [
      {
        title: "Implemented event path",
        state: "Current build",
        code: "OpenSky states (20-second poll)\n  -> Python producer (FDX / UPS filter)\n  -> Redpanda topic: shipments\n  -> FastAPI aiokafka consumer\n  -> WebSocket: /ws/flights\n  -> React state keyed by icao24 or callsign\n  -> Leaflet map marker + popup",
      },
      {
        title: "Current event contract",
        state: "Current build",
        table: { headers: ["Field", "Meaning", "Boundary"], rows: [
          ["icao24", "Aircraft identifier", "Optional in mock records; preferred UI key"],
          ["callsign", "Displayed flight identifier", "Used as fallback key and FDX/UPS filter"],
          ["latitude / longitude", "Current position", "Null and invalid-coordinate handling requires a documented rule"],
          ["velocity", "OpenSky velocity", "Source is meters/second; current UI incorrectly labels kilometers/hour"],
          ["altitude", "Geometric altitude from the OpenSky state", "Optional in the frontend contract"],
          ["timestamp", "OpenSky response time", "Freshness display is planned"],
        ] },
      },
      {
        title: "Why an event broker",
        state: "Current build",
        body: ["The central architecture decision places a Kafka-compatible broker between ingestion and presentation. This creates a clear boundary between the source adapter and downstream consumers. Scale and production fault tolerance require further testing."],
        bullets: [
          "Python keeps source integration and mock generation inspectable.",
          "Redpanda provides a Kafka-compatible development broker with a compact local setup.",
          "FastAPI and aiokafka bridge asynchronous event consumption to a browser protocol.",
          "React and Leaflet provide a direct spatial representation of changing coordinates.",
        ],
      },
      {
        title: "Known implementation boundaries",
        state: "Current build",
        bullets: [
          "The producer starts separately from Docker Compose.",
          "The root requirements file still needs pinned versions for Requests and kafka-python.",
          "Each WebSocket connection creates a consumer in the same consumer group, which can divide events across multiple clients. A broadcast layer is planned.",
          "Reconnect, last-updated, and stale-marker behavior are planned for the browser.",
          "The frontend build succeeds independently. End-to-end reproduction remains pending for this portfolio review.",
        ],
      },
      {
        title: "Path to production",
        state: "Design target",
        code: "Source adapter -> versioned event contract -> broker\n                                      -> one backend consumer\n                                      -> in-memory or durable current-state store\n                                      -> fan-out connection manager\n                                      -> clients with reconnect + freshness state\n                                      -> telemetry for lag, loss, duplicates, and age",
        body: ["A production path would separate event consumption from individual browser connections, retain the latest state by aircraft, and make data age observable. These capabilities define the next implementation stage."],
      },
      {
        title: "Architecture decisions still required",
        state: "Proposed next step",
        table: { headers: ["Decision", "Options", "Evaluation criterion"], rows: [
          ["Fan-out model", "Process-local manager, shared pub/sub, or gateway", "Client consistency, operability, and scale"],
          ["Current-state storage", "Memory, Redis, or durable time-series store", "Recovery, history, cost, and latency"],
          ["Schema contract", "JSON validation or schema registry", "Compatibility and source quality"],
          ["Freshness policy", "Source-specific TTL and degraded states", "User interpretation and false confidence"],
          ["Source strategy", "OpenSky only, mock mode, or licensed feed", "Terms, coverage, rate limits, and reliability"],
        ] },
      },
    ],
  },
  {
    slug: "program-plan",
    label: "DELIVERY LEADERSHIP",
    title: "Delivery & Observability Plan",
    summary: "Sequences the prototype into a measurable task workflow, defines dependencies and ownership, and makes reliability and user-value gates explicit.",
    sections: [
      {
        title: "Milestones and gates",
        state: "Proposed next step",
        table: { headers: ["Milestone", "Deliverable", "Exit gate"], rows: [
          ["1 · Baseline", "Pinned environment, mock dataset, known event path", "One traceable event reaches the rendered map"],
          ["2 · Trust layer", "Units, freshness, connection state, stale expiry", "Failure scenarios are visible and deterministic"],
          ["3 · Core task", "Search, filter, and flight detail", "Specified-flight task passes acceptance tests"],
          ["4 · Reliability", "Fan-out, reconnect, sequence tracing, metrics", "Loss, duplication, recovery, and latency are measured"],
          ["5 · User validation", "Five moderated sessions and synthesis", "User, task, and workflow are supported or revised"],
          ["6 · Pilot decision", "Scorecard and recommendation", "Evidence justifies a bounded non-operational pilot"],
        ] },
      },
      {
        title: "RACI",
        state: "Design target",
        body: ["Gokul owns the current independent prototype. These roles define the minimum team for a future pilot."],
        table: { headers: ["Workstream", "Responsible", "Accountable", "Consulted", "Informed"], rows: [
          ["User workflow and requirements", "Product manager", "Product owner", "Cargo operations users", "Engineering"],
          ["Event contract and backend", "Backend engineer", "Technical lead", "Data-source owner", "Product"],
          ["Map task flow", "Frontend engineer", "Product owner", "Operations users", "Technical lead"],
          ["Reliability evaluation", "QA / platform engineer", "Technical lead", "Product", "Pilot owner"],
          ["Pilot readiness", "TPM", "Pilot owner", "Product, engineering, operations", "Stakeholders"],
        ] },
      },
      {
        title: "RAID log",
        state: "Design target",
        table: { headers: ["Type", "Item", "Response"], rows: [
          ["Risk", "A visual map is mistaken for operational truth", "Expose source, freshness, limits, and non-operational status"],
          ["Risk", "Consumer-group behavior produces inconsistent client views", "Move to one consumer and explicit fan-out before multi-user evaluation"],
          ["Risk", "Source limits or outages create silent staleness", "Instrument source age and visible degraded state"],
          ["Risk", "Incorrect units undermine trust", "Normalize at ingestion and test the displayed contract"],
          ["Assumption", "Cargo coordinators value this task", "Validate before adding broad feature scope"],
          ["Dependency", "A real pilot needs authorized, reliable flight data", "Review source terms and operating requirements"],
        ] },
      },
      {
        title: "Observability contract",
        state: "Design target",
        table: { headers: ["Signal", "Purpose", "Owner"], rows: [
          ["Source poll status and age", "Distinguish current data from source failure", "Source adapter"],
          ["Broker publish/consume offset and lag", "Identify delayed or lost processing", "Platform"],
          ["Event sequence and duplicate count", "Test delivery integrity", "Backend"],
          ["Connected clients and fan-out errors", "Detect inconsistent browser delivery", "Backend"],
          ["Client last-rendered timestamp", "Measure event-to-render behavior", "Frontend"],
          ["Search and detail task events", "Measure task completion and usability", "Product"],
        ] },
      },
      {
        title: "Readiness and rollback",
        state: "Proposed next step",
        bullets: [
          "Pilot entry criterion: source, connection, and stale-data states are visible.",
          "Set latency and reliability targets after measuring a baseline.",
          "Keep a deterministic mock mode for demonstrations and failure testing.",
          "If live data becomes unavailable, stop calling the view live and label the fallback explicitly.",
          "If user research rejects the workflow, revise the user and task before expanding features.",
        ],
      },
    ],
  },
  {
    slug: "validation",
    label: "VALIDATION",
    title: "Validation Status and Test Plan",
    summary: "Records what was independently checked at the pinned commit, what remains unverified, and the reliability and user tests required before stronger claims.",
    sections: [
      {
        title: "Pinned audit",
        state: "Current build",
        table: { headers: ["Check", "Result", "Boundary"], rows: [
          ["Source commit", "fc0ea6ff4c267796fb2271a63443b3f53500ff76", "Public repository snapshot"],
          ["Frontend production build", "Passed", "Confirms the React and TypeScript bundle"],
          ["Python source compilation", "Passed", "Syntax check only"],
          ["Docker Compose configuration", "Parsed with an obsolete-version warning", "Confirms configuration validity; service readiness requires a full run"],
          ["End-to-end OpenSky-to-browser flow", "Status: reproduction pending", "Working-product validation remains open"],
          ["Performance and multi-client behavior", "Status: measurement pending", "Latency, scale, and reliability require a baseline run"],
        ] },
      },
      {
        title: "Functional acceptance suite",
        state: "Proposed next step",
        table: { headers: ["Scenario", "Expected evidence"], rows: [
          ["Mock event", "Known callsign and coordinates appear with a matching source timestamp"],
          ["Live source success", "Valid FDX/UPS records pass the documented schema"],
          ["Invalid coordinate or missing identity", "Record is rejected or visibly quarantined"],
          ["Source failure", "View reports a degraded state and the age of the latest update"],
          ["WebSocket interruption", "Client reports disconnection and recovers after service return"],
          ["Two simultaneous browsers", "Both receive the same sequenced test events"],
          ["Expired aircraft", "Marker becomes stale and is removed according to policy"],
        ] },
      },
      {
        title: "Reliability evaluation",
        state: "Proposed next step",
        table: { headers: ["Measure", "Method", "Publish rule"], rows: [
          ["Event-to-render latency p50/p95", "Correlated timestamps at producer, broker, backend, and browser", "Publish only with environment and sample size"],
          ["Lost and duplicate updates", "Sequence-number reconciliation under deterministic load", "Publish observed rate, duration, and load"],
          ["Reconnect recovery", "Timed controlled interruptions", "Publish results across repeated interruptions"],
          ["Freshness correctness", "Compare displayed state with event age", "Publish false-current and false-stale cases"],
          ["Concurrent-view consistency", "Compare received sequences across clients", "Publish only after fan-out behavior is corrected"],
        ] },
      },
      {
        title: "Usability protocol",
        state: "Proposed next step",
        body: ["Recruit five participants who perform cargo-monitoring or adjacent operational work. Five is the proposed starting sample for the first research round."],
        bullets: [
          "Ask each participant to locate a specified flight, assess its freshness, and explain what they would do next.",
          "Record task success, time, errors, confidence, missing fields, and interpretation of degraded states.",
          "Let participants complete the task in their own way.",
          "Synthesize findings by task and severity, then separate observed behavior from stated preferences.",
        ],
      },
      {
        title: "Claim publication gate",
        state: "Proposed next step",
        table: { headers: ["Claim", "Required evidence"], rows: [
          ["Working end-to-end prototype", "Pinned setup produces a traceable browser event"],
          ["Reliable", "Documented loss, duplication, recovery, and freshness results"],
          ["Low latency", "p50/p95 measurement with environment and sample size"],
          ["Useful for cargo operations", "Task-based research with the target role"],
          ["Reduces monitoring effort", "Baseline comparison in a bounded pilot"],
        ] },
      },
    ],
  },
  {
    slug: "recording-guide",
    label: "DEMO RUNBOOK",
    title: "Recording Guide",
    visibility: "private",
    summary: "Private checklist for a future demo after the event path and product states are validated.",
    sections: [
      {
        title: "Recording gate",
        state: "Proposed next step",
        bullets: [
          "Use the pinned commit and record the exact environment.",
          "Run the infrastructure, backend/frontend services, and producer as separate documented steps.",
          "Prefer deterministic mock data first; label any OpenSky segment as live-source behavior.",
          "Recording entry criterion: units, connection state, and stale-data behavior are correct.",
        ],
      },
      {
        title: "Narrative",
        state: "Proposed next step",
        table: { headers: ["Time", "Show", "Explain"], rows: [
          ["0–15s", "Cargo-monitoring task", "The target user and the unvalidated value hypothesis"],
          ["15–35s", "Event path", "OpenSky or mock source through Redpanda and FastAPI"],
          ["35–60s", "Map and flight detail", "What is implemented and how freshness is shown"],
          ["60–80s", "Controlled disconnect or stale record", "How uncertainty and recovery are exposed"],
          ["80–90s", "Limitations", "This prototype supports monitoring research; operational dispatch and safety decisions stay with authoritative systems"],
        ] },
      },
    ],
  },
];
