import type { ProjectArtifact } from "../../types";

export const complianceArtifacts: ProjectArtifact[] = [
  {
    slug: "prd",
    label: "PRODUCT DEFINITION",
    title: "Product Requirements Document",
    summary: "A product brief for the deterministic container-policy prototype, covering policy ownership, requirements, exceptions, metrics, and rollout.",
    sections: [
      {
        title: "Context and source",
        state: "Current build",
        body: ["I created this portfolio PRD after completing the prototype. It documents the current implementation and the proposed product path."],
        table: { headers: ["Field", "Value"], rows: [
          ["Version", "2.0"],
          ["Updated", "September 2, 2026"],
          ["Source commit", "d2e0b787e47c1f12e4582dd735c55f151396331a"],
          ["Evidence boundary", "Repository behavior is inspectable; the customer problem, policy fit, value, and rollout remain hypotheses until validated"],
        ] },
      },
      {
        title: "Product brief",
        state: "Design target",
        body: ["Build a narrow, deterministic release gate that applies the same container policy every time, explains each finding, and gives CI or a reviewer an enforcement signal they can act on."],
        table: { headers: ["PRD field", "Decision"], rows: [
          ["Status", "Implemented CLI/daemon prototype; CI workflow and exception lifecycle planned"],
          ["Product owner", "Gokul Gopalakrishnan · independent end-to-end build"],
          ["Primary-user hypothesis", "Platform or release engineer enforcing container policy"],
          ["Policy owner", "Security or governance stakeholder who defines rule meaning and severity"],
          ["Target job", "Detect specified violations before release and retain an inspectable result"],
          ["Hypothesized current workflow", "Manual review of container labels and exposed ports against documented policy"],
          ["Product boundary", "Deterministic policy-as-code automation using inspectable rules"],
        ] },
      },
      {
        title: "Problem and open assumptions",
        state: "Design target",
        body: ["Problem hypothesis: policy is applied inconsistently when rules live only in documentation or manual checklists. Controlled cases verify deterministic inspection behavior. An advisory pilot would measure the frequency, cost, and organizational impact of real release-policy misses."],
        table: { headers: ["Statement", "Evidence state", "Implication"], rows: [
          ["Required labels and forbidden ports can be inspected through Docker", "Implemented", "These rules can be evaluated deterministically"],
          ["Manual checks create inconsistent release decisions", "Unvalidated workflow hypothesis", "Confirm with platform/release interviews and historical examples"],
          ["These two rule families matter to the target policy owner", "Policy assumption", "A real pilot requires named rule ownership and severity"],
          ["CI enforcement improves release quality", "Unvalidated value hypothesis", "Measure scenario accuracy, review burden, and remediation workflow first"],
        ] },
      },
      {
        title: "Outcome to validate",
        state: "Design target",
        table: { headers: ["Layer", "Desired change", "Why it matters"], rows: [
          ["User outcome", "Know exactly which defined policy checks passed or failed before release", "Replaces interpretation with an inspectable decision"],
          ["Workflow outcome", "Route each actionable finding to remediation or an approved exception", "Named ownership turns each violation into a clear action"],
          ["Product behavior", "Separate versioned policy, inspection, evidence, and process exit status", "Makes rule changes and automation behavior reviewable"],
          ["Business hypothesis", "Reduce preventable release-policy misses and review effort", "Requires CI workflow data before any time or risk claim"],
        ] },
      },
      {
        title: "End-to-end release journey",
        state: "Design target",
        table: { headers: ["Step", "User intent", "Product response", "Status"], rows: [
          ["1 · Select policy", "Apply the approved rule version", "Load and validate JSON before inspecting Docker", "Implemented"],
          ["2 · Define population", "Know which running containers are in scope", "Enumerate containers through the Docker client", "Implemented"],
          ["3 · Evaluate", "Apply the same rules to every subject", "Check required labels and forbidden exposed ports", "Implemented"],
          ["4 · Inspect evidence", "Understand each pass, violation, or error", "Write structured per-container findings", "Implemented"],
          ["5 · Enforce", "Allow CI to act on the result", "Return a CI-compatible process status", "Implemented locally"],
          ["6 · Resolve", "Assign remediation or approve an exception", "Named owner, approval, expiry, and evidence retention", "Proposed P1"],
        ] },
      },
      {
        title: "Release scope and non-goals",
        state: "Design target",
        table: { headers: ["Priority", "In scope", "Boundary"], rows: [
          ["P0", "Validate versioned policy before audit", "Invalid policy fails before infrastructure inspection"],
          ["P0", "Inspect required labels", "Configured label presence; semantic ownership verification is planned"],
          ["P0", "Inspect forbidden container and published ports", "Scope covers configured port values"],
          ["P0", "Produce JSON evidence and exit status", "Hosted evidence storage and signed reports are planned"],
          ["P1", "Exception lifecycle and remediation owner", "Status: planned"],
          ["P1", "CI artifact retention and signed policy distribution", "Status: planned"],
          ["Out of scope", "Formal compliance, image/package scanning, Kubernetes, autonomous approval, AI decisions", "The gate covers a narrow deterministic policy boundary"],
        ] },
      },
      {
        title: "Requirements and acceptance criteria",
        state: "Design target",
        table: { headers: ["Type", "Requirement", "Acceptance criterion", "Status"], rows: [
          ["User", "Understand a violation", "Every finding names the container, rule, observed state, and reason", "Implemented"],
          ["Policy", "Reject invalid governance input", "Malformed policy exits before Docker inspection and returns an error state", "Implemented"],
          ["System", "Isolate per-container failures", "One inspection error is recorded while preserving other container results", "Implemented"],
          ["Integration", "Signal CI outcome", "Clean audit returns success; violations or fatal errors return nonzero", "Implemented"],
          ["Security", "Protect privileged Docker access", "Execution environment and socket permissions must be explicitly controlled", "Required before pilot"],
          ["Workflow", "Resolve or except a finding", "Every bypass has approver, reason, owner, and expiration", "Proposed P1"],
        ] },
      },
      {
        title: "Success measures",
        state: "Proposed next step",
        table: { headers: ["Metric", "Baseline / target", "How to measure", "Decision supported"], rows: [
          ["Scenario precision / recall", "Establish on a labeled suite", "Controlled compliant, violating, invalid, and failure cases", "Are rules implemented correctly?"],
          ["Blocking false-positive rate", "Must be agreed before enforcement", "Advisory findings reviewed by policy owner", "Can the gate move from advisory to blocking?"],
          ["Audit runtime and system-error rate", "Baseline in target CI environment", "Telemetry by policy version and audit population", "Is the integration operationally acceptable?"],
          ["Time to understand / remediate", "Establish with release engineers", "Timed finding-review task and workflow events", "Does evidence shorten resolution?"],
          ["Unowned or expired exceptions", "Proposed guardrail; threshold requires policy-owner approval", "Exception registry with owner, approval, and expiration", "Is bypass risk controlled?"],
        ] },
      },
      {
        title: "Threats, failure states, and fallback",
        state: "Design target",
        table: { headers: ["Risk or failure", "Required behavior", "Fallback / owner"], rows: [
          ["Privileged Docker API exposure", "Treat access as privileged and often root-equivalent; use an isolated disposable runner, rootless daemon, or constrained proxy", "Keep the host socket isolated from untrusted code; platform owner controls the boundary"],
          ["Tampered or stale policy", "Verify approved version and integrity before audit", "Fail closed; policy owner republishes"],
          ["Incomplete audit population", "Report scope and enumeration errors explicitly", "Release engineer reviews coverage"],
          ["Time-of-check/time-of-use change", "Record audit time and subject identity", "Re-run at the release boundary"],
          ["False positive or necessary exception", "Remain advisory until exception workflow exists", "Use documented manual release review"],
          ["Docker connection failure", "Return a system error and block policy-pass status", "Block automation and fall back to manual review"],
        ] },
      },
      {
        title: "Rollout plan",
        state: "Proposed next step",
        table: { headers: ["Stage", "What happens", "Exit gate"], rows: [
          ["1 · Controlled suite", "Run labeled policy and system-failure scenarios", "Expected findings and exit behavior match"],
          ["2 · CI shadow mode", "Publish evidence while release remains advisory", "False positives, runtime, and coverage reviewed"],
          ["3 · Reviewer calibration", "Policy owner and release engineers adjudicate findings", "Severity, remediation, and exceptions are unambiguous"],
          ["4 · Limited blocking", "Enforce only approved P0 rules on a bounded service group", "Rollback, bypass, ownership, and artifact retention are operational"],
        ] },
        body: ["The existing manual release review remains the rollback path. Blocking mode begins after the policy owner accepts scenario accuracy and the exception lifecycle is operational."],
      },
      {
        title: "Open questions before enforcement",
        state: "Proposed next step",
        bullets: [
          "Who owns each policy rule, severity, version, and approval?",
          "Which container population and release event define the enforcement boundary?",
          "How are exceptions approved, expired, audited, and revoked?",
          "What report integrity and retention rules are required for release evidence?",
          "When should a container inspection error block release versus route to review?",
        ],
      },
    ],
  },
  {
    slug: "technical-design",
    label: "TECHNICAL JUDGMENT",
    title: "Policy & Technical Design",
    summary: "Documents the policy contract, modular inspection path, report and exit behavior, Docker-socket threat boundary, and alternatives considered.",
    sections: [
      {
        title: "Architecture",
        state: "Current build",
        code: "policy.json ─> PolicyIngestor ─> typed GovernancePolicy\n                                      ↓\nDocker socket ──────────────────> Auditor\n                                  ├─ required label checks\n                                  └─ forbidden port checks\n                                      ↓\n                                  AuditReport ─> JSON evidence + CLI exit status",
      },
      {
        title: "Policy contract",
        state: "Current build",
        body: ["The JSON policy provides a version, required label keys, and forbidden port values. Validation occurs before the Docker connection and returns an error state for malformed governance input."],
        bullets: [
          "Required labels express ownership and operating context.",
          "Forbidden ports express a narrow network-exposure rule.",
          "Rule changes happen in the policy file while the inspection engine remains stable.",
          "Boolean values are rejected where integer port values are required.",
        ],
      },
      {
        title: "Result and exit contract",
        state: "Current build",
        table: { headers: ["Condition", "Report behavior", "Process behavior"], rows: [
          ["All inspected containers pass", "Structured per-container results and summary", "Exit 0"],
          ["Policy violation exists", "Explicit violation with container and rule context", "Exit 1"],
          ["Container inspection error", "Error retained alongside other results", "Audit remains in an error state"],
          ["Invalid policy or fatal Docker error", "Actionable fatal error", "Exit 1"],
        ] },
      },
      {
        title: "Technology decisions",
        state: "Current build",
        bullets: [
          "Python and the Docker SDK keep inspection logic small and directly testable.",
          "JSON makes the current policy readable and versionable. Enterprise distribution and signing remain planned capabilities.",
          "Modular ingestion, auditing, reporting, and service control keep the first release focused while supporting new rules.",
          "Docker Compose provides controlled compliant and non-compliant demo fixtures.",
        ],
      },
      {
        title: "Docker-socket threat model",
        state: "Design target",
        table: { headers: ["Threat", "Required control before production"], rows: [
          ["Docker socket grants privileged host visibility", "Run in an isolated, least-privileged execution environment and keep the socket isolated from untrusted code"],
          ["Container metadata may reveal sensitive operating details", "Limit report access and redact or scope retained evidence"],
          ["Policy tampering changes enforcement", "Sign and version policy; restrict write authority"],
          ["Auditor compromise becomes a host risk", "Pin dependencies, isolate runtime, monitor access, and separate collection from decision storage"],
        ] },
      },
      {
        title: "Alternatives and boundary",
        state: "Design target",
        body: ["OPA or an admission-policy platform would be stronger choices for a broad production policy program. This prototype stays narrow to make policy ingestion, evidence, errors, and CI behavior inspectable. A future LLM may explain a finding or propose cited remediation, but deterministic policy code must retain release authority."],
      },
    ],
  },
  {
    slug: "program-plan",
    label: "DELIVERY LEADERSHIP",
    title: "Rollout Plan",
    summary: "Defines policy ownership, advisory-to-blocking rollout, exception dependencies, RAID controls, readiness gates, and rollback behavior.",
    sections: [
      {
        title: "Milestones",
        state: "Design target",
        table: { headers: ["Milestone", "Exit gate"], rows: [
          ["1 · Policy definition", "One narrow release decision, policy owner, severity, and non-goals approved"],
          ["2 · Contract baseline", "Input, rule, result, error, and missing-evidence behavior documented"],
          ["3 · Deterministic MVP", "Rules, reports, exit behavior, and fixtures are inspectable"],
          ["4 · Advisory pilot", "Findings run in CI as advisory results; false positives and remediation effort reviewed"],
          ["5 · Exception workflow", "Owner, justification, approval, expiry, and audit retention implemented"],
          ["6 · Blocking decision", "Readiness scorecard approved by policy and release owners"],
        ] },
      },
      {
        title: "RACI",
        state: "Design target",
        body: ["Gokul designed and built the current demonstration. The table defines the minimum operating ownership for a future rollout."],
        table: { headers: ["Workstream", "Responsible", "Accountable", "Consulted", "Informed"], rows: [
          ["Policy meaning and severity", "Security engineer", "Policy owner", "Release and service owners", "TPM"],
          ["Product requirements", "Product owner", "Product owner", "Platform, security, release", "Engineering"],
          ["Rule implementation", "Software engineer", "Technical lead", "Policy owner", "Product owner"],
          ["Scenario validation", "Security/QA engineer", "Policy owner", "Engineering", "TPM"],
          ["Rollout and exceptions", "TPM", "Release owner", "Security and service teams", "Stakeholders"],
        ] },
      },
      {
        title: "Exception lifecycle dependency",
        state: "Proposed next step",
        table: { headers: ["State", "Required behavior"], rows: [
          ["Finding created", "Named rule, subject, evidence, severity, and remediation owner"],
          ["Exception requested", "Business reason, compensating control, risk owner, and requested expiry"],
          ["Decision", "Policy-owner approval or rejection retained with identity and timestamp"],
          ["Active exception", "Visible to CI and reviewers as a distinct governed state"],
          ["Expiry", "Automatically returns to enforcement unless explicitly renewed"],
        ] },
      },
      {
        title: "RAID log",
        state: "Design target",
        table: { headers: ["Type", "Item", "Response"], rows: [
          ["Risk", "A green result is mistaken for formal compliance", "Use ‘policy check passed’; preserve scope and limitations"],
          ["Risk", "Rule code drifts from policy intent", "Version rules and require policy-owner approval"],
          ["Risk", "False positives block delivery", "Run advisory first; measure and review every blocking candidate"],
          ["Risk", "Privileged Docker access expands blast radius", "Isolate runtime and minimize socket exposure"],
          ["Dependency", "Production rollout needs an exception owner", "Blocking entry criterion: approved exception lifecycle"],
          ["Decision", "Deterministic checks own release status", "Keep any future AI layer explanatory and cited"],
        ] },
      },
      {
        title: "Readiness and rollback",
        state: "Proposed next step",
        bullets: [
          "Policy owner approves rule semantics, severity, and version.",
          "Scenario suite includes pass, fail, malformed, unavailable, and exception cases.",
          "Advisory telemetry establishes false-positive and runtime behavior.",
          "Every blocking finding has a remediation and escalation owner.",
          "Rollback changes the gate to advisory mode while continuing to retain findings.",
          "Emergency bypass requires named approval, a recorded reason, and an expiration date.",
        ],
      },
    ],
  },
  {
    slug: "validation",
    label: "VALIDATION",
    title: "Scenario Validation Pack",
    summary: "Defines the current controlled fixtures and the failure, ambiguity, and rollout scenarios required before CI enforcement.",
    sections: [
      {
        title: "Current controlled demo",
        state: "Current build",
        table: { headers: ["Fixture", "Expected result", "Purpose"], rows: [
          ["Compliant web container", "Required labels are present and exposed ports meet policy", "Positive path"],
          ["Rogue API container", "Missing required governance labels", "Ownership-metadata failure"],
          ["Exposed database container", "Forbidden Redis port detected", "Network-exposure failure"],
        ] },
      },
      {
        title: "Functional scenario suite",
        state: "Current build",
        table: { headers: ["Scenario", "Expected behavior"], rows: [
          ["Valid policy", "Loads into the typed policy model before inspection"],
          ["Missing policy keys", "Fails before Docker inspection"],
          ["Boolean forbidden port", "Type validation rejects the value before inspection"],
          ["Missing required label", "Container and missing label key appear in violations"],
          ["Forbidden port", "Container and port appear in violations"],
          ["Mixed audit population", "Successful inspections remain available even if one container errors"],
        ] },
      },
      {
        title: "Additional gate scenarios",
        state: "Proposed next step",
        bullets: [
          "Docker socket unavailable or permission denied.",
          "Unknown or unsigned policy version.",
          "Policy hot-reload introduces invalid input during daemon operation.",
          "Approved exception is active, expired, or missing an owner.",
          "Evidence retention or upload fails.",
          "The configured prefix returns zero target containers.",
        ],
      },
      {
        title: "Advisory-pilot scorecard",
        state: "Proposed next step",
        table: { headers: ["Measure", "Blocking decision"], rows: [
          ["Scenario precision and recall", "Rules behave as the policy owner expects on labeled cases"],
          ["False-positive review", "Blocking candidates stay within the agreed delivery-friction threshold"],
          ["Median and tail audit runtime", "Gate fits the release path and exposes timeouts clearly"],
          ["Remediation completion time", "Findings are understandable and actionable"],
          ["Unowned or expired exceptions", "Governance workflow identifies and closes permanent bypass risk"],
          ["System-error rate", "Infrastructure failure is distinguishable from non-compliance"],
        ] },
      },
      {
        title: "Enforcement criteria",
        state: "Proposed next step",
        body: ["Enable blocking only for rules with an accountable policy owner, labeled scenario coverage, acceptable advisory behavior, a named remediation path, and an auditable exception lifecycle. Final readiness combines unit tests with pilot behavior and owner approval."],
      },
    ],
  },
  {
    slug: "recording-guide",
    label: "DEMO RUNBOOK",
    title: "Recording Guide",
    // Private working material. Change to "public" only after a validated video URL exists.
    visibility: "private",
    summary: "A deterministic 60–90 second CLI walkthrough of policy, controlled containers, violations, evidence, and expected enforcement status.",
    sections: [
      {
        title: "One-command setup",
        state: "Current build",
        body: ["Run from the AI-Continuous-Compliance repository with Docker Desktop or Docker Engine running. The script falls back to committed sample output when Docker is unavailable; use the live Docker path for the recording."],
        code: "python3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\nchmod +x demo/run_demo.sh\n./demo/run_demo.sh",
      },
      {
        title: "Manual recording sequence",
        state: "Current build",
        code: "docker compose -f demo/docker-compose.demo.yml up -d\ndocker ps --filter name=cc-demo\ncat policy.json\npython3 -m compliance.main --policy policy.json --output demo/audit_log.json --container-prefix cc-demo\n# Exit 1 is expected because two fixtures intentionally violate policy.\npython3 demo/print_report.py demo/audit_log.json\ndocker compose -f demo/docker-compose.demo.yml down",
      },
      {
        title: "60–90 second narrative",
        state: "Current build",
        table: { headers: ["Time", "Show", "Say"], rows: [
          ["0–10s", "Policy and three fixtures", "This is for a platform or release engineer who needs a repeatable, inspectable policy check before release."],
          ["10–25s", "Required labels and forbidden ports", "The rule lives outside the engine in versioned JSON and is validated before infrastructure inspection."],
          ["25–50s", "Run the audit", "The auditor checks the controlled container population and records each result independently."],
          ["50–70s", "Printed findings and JSON", "One container passes; two expose intentional label and port violations with structured evidence."],
          ["70–85s", "Exit behavior", "A nonzero exit is expected because violations exist. Describe the system as deterministic policy automation with a narrow, inspectable rule set."],
        ] },
      },
      {
        title: "Safe claims and boundaries",
        state: "Current build",
        table: { headers: ["Supported description", "Excluded claim"], rows: [
          ["The auditor applies implemented label and port rules reproducibly", "The system proves a container or organization is compliant"],
          ["The JSON report and exit code are CI-compatible", "The project is deployed as a production release gate"],
          ["The code is deterministic", "The repository name means the implementation uses AI"],
        ] },
      },
    ],
  },
];
