import type { ProjectArtifact } from "../../types";

export const sensorArtifacts: ProjectArtifact[] = [
  {
    slug: "prd",
    label: "AI / ML PRODUCT DEFINITION",
    title: "AI/ML Product Requirements Document",
    summary: "A retrospective portfolio PRD structured from the target user backward for a human-owned reliability workflow, covering the user decision, AI rationale, baseline comparison, evaluation contract, failure modes, and launch gates.",
    sections: [
      {
        title: "Artifact status and provenance",
        state: "Current build",
        body: ["Retrospective portfolio PRD created after the prototype; not a contemporaneous employer or team artifact."],
        table: { headers: ["Field", "Value"], rows: [
          ["Version", "2.0"],
          ["Updated", "September 2, 2026"],
          ["Source commit", "8122928302dc85d776e5adbf803171634a636ef3"],
          ["Evidence boundary", "Repository behavior is inspectable; the customer problem, value, operating validity, and rollout remain hypotheses until validated"],
        ] },
      },
      {
        title: "Product brief",
        state: "Design target",
        body: ["Build a review-support workflow for scarce-label condition monitoring. The product ranks unusual vibration windows for inspection; a reliability engineer—not the model—owns diagnosis and maintenance decisions."],
        table: { headers: ["PRD field", "Decision"], rows: [
          ["Status", "Implemented public-data prototype; pinned comparative evaluation is still required"],
          ["Product owner", "Gokul Gopalakrishnan · independent end-to-end build"],
          ["Primary-user hypothesis", "Reliability engineer reviewing equipment-condition data"],
          ["Target job", "Find the small set of vibration windows that deserve closer inspection"],
          ["Hypothesized current workflow", "Review fixed alarms, trends, or raw signals without a learned healthy-baseline ranking"],
          ["Value hypothesis", "Increase review coverage without creating an uncontrolled false-alert burden"],
          ["Decision boundary", "Review prioritization only; no failure prediction, work order, shutdown, or maintenance recommendation"],
        ] },
      },
      {
        title: "Problem evidence and assumptions",
        state: "Design target",
        body: ["Problem hypothesis: reliability teams may have abundant healthy history but too few representative failure labels for supervised prediction. Public CWRU data proves the pipeline can be exercised; it does not validate the workflow, operating distribution, or value in a plant."],
        table: { headers: ["Statement", "Evidence state", "Implication"], rows: [
          ["Healthy-only detector training is technically possible", "Implemented", "Failure examples are not required during training"],
          ["Reliability engineers face an unmanageable review burden", "Unvalidated workflow hypothesis", "Measure alerts per 1,000 windows and observed review time"],
          ["CWRU behavior transfers to plant assets", "Unsupported assumption", "Require independent-data shadow evaluation before any plant claim"],
          ["Anomaly ranking improves the maintenance workflow", "Unvalidated value hypothesis", "Test whether reviewers reach a defensible next step faster or with better coverage"],
        ] },
      },
      {
        title: "Data provenance and governance",
        state: "Proposed next step",
        body: ["The prototype fetches public CWRU Bearing Data Center files so the pipeline can be exercised. A decision-grade evaluation needs a frozen, reviewable data manifest rather than relying on mutable download locations."],
        table: { headers: ["Control", "Current state", "Required evidence"], rows: [
          ["Source", "CWRU Bearing Data Center public download source", "Record source page, retrieval date, and intended evaluation use"],
          ["File registry", "13 source files or URLs encoded in the repository", "Freeze exact files, labels, operating conditions, and roles in a manifest"],
          ["Version identity", "No published checksum manifest", "Publish file sizes and cryptographic checksums with the pinned run"],
          ["Usage terms", "No license or commercial-use claim is made", "Verify and record applicable usage terms before redistribution or commercial reuse"],
          ["Split lineage", "Contiguous split logic exists in code", "Publish file-to-window lineage, labels, checksums, and train/validation/test roles"],
        ] },
      },
      {
        title: "Why ML—and where it stops",
        state: "Design target",
        body: ["A learned healthy baseline can rank multivariate or waveform deviations without requiring representative failure labels during training. ML is justified only if it improves useful detection at an acceptable review burden relative to simpler rules."],
        table: { headers: ["Decision", "Rationale", "Guardrail"], rows: [
          ["Augment, do not automate", "The model can prioritize evidence but cannot understand maintenance context", "A human owns diagnosis and action"],
          ["Compare simple and complex models", "Isolation Forest may be sufficient and easier to operate", "No LSTM preference without comparative evidence"],
          ["Expose continuous scores and thresholds", "Review burden changes with the operating point", "Do not hide the tradeoff behind a binary alert"],
          ["Keep a non-ML baseline", "Fixed or statistical rules establish whether ML adds value", "Add and report the baseline before launch selection"],
        ] },
      },
      {
        title: "End-to-end review journey",
        state: "Design target",
        table: { headers: ["Step", "User intent", "Product response", "Status"], rows: [
          ["1 · Load evidence", "Open a recording or prepared feature set", "Validate the supported input and model contract", "Implemented"],
          ["2 · Score windows", "Find deviations from healthy behavior", "Run the persisted detector and threshold", "Implemented"],
          ["3 · Prioritize", "See the most unusual regions first", "Display anomaly timeline, scores, and flagged windows", "Implemented"],
          ["4 · Adjust sensitivity", "Understand alert-burden tradeoffs", "Show threshold sensitivity and changed flag counts", "Implemented"],
          ["5 · Inspect context", "Decide whether engineering investigation is warranted", "Review source traces and available labels", "Implemented prototype"],
          ["6 · Disposition", "Record the next engineering action and feedback", "Reviewer feedback and label loop", "Proposed"],
        ] },
      },
      {
        title: "Release scope and non-goals",
        state: "Design target",
        table: { headers: ["Priority", "In scope", "Boundary"], rows: [
          ["P0", "Public CWRU ingestion and fixed window contract", "Public bearing data only"],
          ["P0", "Healthy-only Isolation Forest and LSTM autoencoder", "Candidate comparison; no winner declared"],
          ["P0", "Leakage-aware contiguous splits with boundary gaps", "Controls overlap leakage; does not solve domain shift"],
          ["P0", "Provisional 0.5% validation false-positive budget", "Engineering policy, not a validated user requirement"],
          ["P0", "Streamlit review of flags, traces, scores, and sensitivity", "Review aid only"],
          ["P1", "Reviewer feedback, disposition, and label capture", "Not implemented"],
          ["Out of scope", "RUL prediction, autonomous action, work orders, production savings, plant-validity claims", "Human-owned maintenance workflow"],
        ] },
      },
      {
        title: "Requirements and acceptance criteria",
        state: "Design target",
        table: { headers: ["Type", "Requirement", "Acceptance criterion", "Status"], rows: [
          ["User", "Inspect a flagged region", "Reviewer can connect each flag to its source window, score, and visible signal", "Implemented"],
          ["User", "Understand sensitivity", "Changing threshold updates the visible review queue without implying recalibrated validity", "Implemented"],
          ["Data", "Prevent overlap leakage", "Train, validation, and test windows are contiguous with boundary gaps", "Implemented"],
          ["Model", "Compare candidate approaches", "Both models use the same frozen split and report the same evaluation contract", "Protocol defined; pinned run required"],
          ["System", "Load a known artifact and feature contract", "Missing artifacts are labeled and route to exploratory fitting; corrupt or incompatible artifacts must fail with actionable guidance", "Missing-artifact path implemented; compatibility handling proposed"],
          ["Guardrail", "Keep action human-owned", "UI language never converts an anomaly flag into a failure or maintenance recommendation", "Required"],
        ] },
      },
      {
        title: "Metric tree and evaluation contract",
        state: "Proposed next step",
        table: { headers: ["Metric", "Baseline / target", "How to measure", "Decision supported"], rows: [
          ["Recall at fixed false-positive burden", "Report; no target before error-cost review", "Frozen held-out manifest at the provisional policy", "Does the detector surface known abnormal windows?"],
          ["Alerts per 1,000 windows", "Compare with simple baseline and reviewer capacity", "Queue count by recording and threshold", "Is review burden operationally manageable?"],
          ["Precision and false-alert examples", "Report with sample context", "Held-out confusion matrix and reviewed traces", "What creates avoidable work?"],
          ["Slice performance", "Report by recording, load, location, and severity", "Predeclared slice table", "Where does performance break?"],
          ["Repeated-run stability", "Report variance across fixed seeds", "Pinned environment and repeated runs", "Is model selection reproducible?"],
          ["Review time and appropriate reliance", "Establish with target reviewers", "Task study with decisions and confidence rationale", "Does the product help rather than encourage overtrust?"],
          ["Latency and artifact footprint", "Baseline on target hardware", "Timed scoring run and persisted size", "Is the chosen model worth its operating cost?"],
        ] },
      },
      {
        title: "Failure taxonomy and fallback",
        state: "Design target",
        table: { headers: ["Failure mode", "Detection / control", "Fallback or response"], rows: [
          ["Overlapping-window leakage", "Contiguous splits, boundary gaps, published split manifest", "Invalidate the run if leakage tests fail"],
          ["Excessive false alerts", "Alert count, precision, reviewed false positives", "Raise threshold or revert to existing review workflow"],
          ["Missed abnormal behavior", "Recall, false-negative examples, condition slices", "Do not use as a sole inspection gate"],
          ["Load, speed, or asset domain shift", "Input distribution and slice monitoring", "Route out-of-domain data to human review; recalibrate before use"],
          ["Unstable threshold or model", "Repeated-run and calibration monitoring", "Freeze prior accepted artifact"],
          ["Model overtrust", "Interface language, source evidence, human disposition", "Require reviewer rationale and no autonomous action"],
          ["Artifact unavailable", "Explicit load failure", "Use the existing reliability workflow; exploratory fitting is not equivalent"],
        ] },
      },
      {
        title: "Rollout and decision gates",
        state: "Proposed next step",
        table: { headers: ["Stage", "What happens", "Exit gate"], rows: [
          ["1 · Evidence release", "Publish commit, environment, split manifest, baseline, model comparison, slices, and failure examples", "Results reproduce from the pinned manifest"],
          ["2 · Usability study", "Observe 3–5 reliability or engineering-adjacent reviewers", "Users can inspect flags, explain uncertainty, and choose a defensible next step"],
          ["3 · External-data shadow", "Score independent or authorized data without triggering action", "Domain shift, review burden, and misses are understood"],
          ["4 · Human-reviewed pilot", "Use on a bounded workflow with monitoring and rollback", "Reviewer ownership, escalation, drift, and threshold-change approval are operational"],
        ] },
        body: ["Launch selection compares the simple baseline, Isolation Forest, and LSTM on useful detection, review burden, stability, latency, and complexity. Model sophistication is not itself a release criterion."],
      },
      {
        title: "Open questions before pilot",
        state: "Proposed next step",
        bullets: [
          "Which reliability role owns review and what decision follows a flagged window?",
          "What false-alert burden can the target workflow absorb?",
          "What is the cost of a missed event relative to an unnecessary investigation?",
          "Which operating conditions require separate calibration or model versions?",
          "What feedback can be captured as a trustworthy label, and who approves retraining?",
          "What monitoring signal should trigger threshold rollback or model retirement?",
        ],
      },
    ],
  },
  {
    slug: "technical-design",
    label: "TECHNICAL JUDGMENT",
    title: "ML System Design",
    summary: "Documents ingestion, leakage controls, feature and waveform paths, threshold calibration, persistence, review UI, and production monitoring considerations.",
    sections: [
      {
        title: "System architecture",
        state: "Current build",
        code: "13 CWRU recordings\n        ↓\n1,024-sample windows · 512-sample hop\n        ↓\nContiguous train / validation / test split with boundary gaps\n        ↓\n┌────────────────────────┬──────────────────────────┐\n│ five condition features│ raw waveform windows     │\n│ Isolation Forest       │ LSTM autoencoder         │\n└────────────────────────┴──────────────────────────┘\n        ↓\nvalidation threshold calibration · 0.5% provisional FPR budget\n        ↓\nflagged-window review in Streamlit",
      },
      {
        title: "Data and leakage controls",
        state: "Current build",
        bullets: [
          "Drive-end accelerometer signals are downloaded from the public CWRU Bearing Data Center.",
          "Fifty-percent-overlapping windows create near-neighbor dependence; random splitting would leak highly similar windows across sets.",
          "Normal windows are split contiguously within each recording, and boundary windows are dropped between segments.",
          "Fault windows remain test-only so neither detector sees fault examples during training.",
        ],
      },
      {
        title: "Candidate models",
        state: "Current build",
        table: { headers: ["Path", "Input", "Product tradeoff"], rows: [
          ["Isolation Forest", "Five engineered condition features", "More interpretable, lighter runtime, may miss waveform detail"],
          ["LSTM autoencoder", "Raw 1,024-sample windows reshaped to 64 × 16", "Richer temporal representation, higher complexity and runtime cost"],
          ["Threshold policy", "99.5th percentile of healthy validation scores", "Makes provisional alert burden explicit but still requires user validation"],
        ] },
      },
      {
        title: "Persistence and review path",
        state: "Current build",
        bullets: [
          "The Isolation Forest scaler, model, threshold, and feature contract are persisted with Joblib.",
          "The LSTM model and threshold metadata are persisted separately.",
          "The Streamlit app avoids importing TensorFlow for the lightweight review path.",
          "A reviewer can use the bundled labeled CSV, inspect anomaly counts, feature traces, score traces, and sensitivity changes.",
        ],
      },
      {
        title: "Stack rationale",
        state: "Current build",
        table: { headers: ["Technology", "Role"], rows: [
          ["NumPy / Pandas / SciPy", "Signal arrays, feature tables, and statistical feature extraction"],
          ["scikit-learn", "Scaling, Isolation Forest, and evaluation metrics"],
          ["TensorFlow / Keras", "LSTM autoencoder training and persistence"],
          ["Joblib", "Lightweight detector artifact"],
          ["Streamlit / Matplotlib", "Operator-facing review and threshold visualization"],
        ] },
      },
      {
        title: "Production monitoring design",
        state: "Proposed next step",
        bullets: [
          "Monitor input sampling rate, missingness, amplitude distribution, operating condition, and score drift.",
          "Track alerts per asset-hour, reviewer dispositions, false-alert feedback, latency, and artifact version.",
          "Require approval and replay evaluation before threshold or model changes.",
          "Separate monitoring failure from a healthy-equipment conclusion.",
        ],
      },
    ],
  },
  {
    slug: "evaluation",
    label: "AI / ML VALIDATION",
    title: "Reproducible Evaluation Protocol",
    summary: "Specifies the pinned run, baselines, slices, error analysis, runtime evidence, and publication gate required before any model-quality metric appears on the homepage.",
    sections: [
      {
        title: "Publication gate",
        state: "Proposed next step",
        body: ["No precision, recall, F1, latency, or model-comparison claim is published on the portfolio homepage until a clean run is tied to a public commit, environment, dataset registry, configuration, split manifest, and saved metrics artifact."],
      },
      {
        title: "Run manifest",
        state: "Proposed next step",
        table: { headers: ["Required field", "Purpose"], rows: [
          ["Repository commit and run date", "Tie the result to inspectable code"],
          ["Python and dependency versions", "Expose runtime variability"],
          ["Dataset file registry and hashes", "Fix the evaluated population"],
          ["Window, hop, gap, and split indices", "Make leakage controls inspectable"],
          ["Random seeds and model parameters", "Support repeated runs"],
          ["Threshold source and quantile", "Separate calibration behavior from test results"],
        ] },
      },
      {
        title: "Baseline and candidates",
        state: "Proposed next step",
        bullets: [
          "Simple non-ML feature threshold, if implemented, to test whether model complexity is justified.",
          "Isolation Forest on the five implemented features.",
          "LSTM autoencoder on raw windows.",
          "No winner selected until useful detection, alert burden, latency, reproducibility, and complexity are compared together.",
        ],
      },
      {
        title: "Required results",
        state: "Proposed next step",
        table: { headers: ["Evidence", "Why it matters"], rows: [
          ["Precision, recall, F1, and confusion matrix", "Basic held-out behavior with class context"],
          ["Alerts per 1,000 windows", "Translate threshold behavior into review burden"],
          ["Results by recording, fault location, size, and load where available", "Expose important performance variation"],
          ["Repeated seeded runs", "Show stability rather than one favorable run"],
          ["True-positive, false-positive, and false-negative waveforms", "Make failure modes inspectable"],
          ["Training/scoring time and artifact size", "Support an operating decision, not only model quality"],
        ] },
      },
      {
        title: "Evaluation status",
        state: "Current build",
        body: ["The repository implements evaluation code and publishes result values in its README. This portfolio deliberately withholds those values until the full pinned-run protocol above is reproduced and stored. Implemented evaluation logic is not the same as independently verified model evidence."],
      },
    ],
  },
  {
    slug: "model-card",
    label: "RESPONSIBLE DELIVERY",
    title: "Model & Failure Card",
    summary: "Defines intended use, out-of-scope decisions, dataset limits, human oversight, known failure classes, and controls required before a pilot.",
    sections: [
      {
        title: "Intended and prohibited use",
        state: "Design target",
        table: { headers: ["Intended", "Out of scope"], rows: [
          ["Rank vibration windows for reliability-engineer review", "Predict remaining useful life or imminent failure probability"],
          ["Compare detector operating tradeoffs on public data", "Generalize to plant assets without recalibration and validation"],
          ["Support investigation with inspectable signals", "Trigger safety-critical control, shutdown, or maintenance automatically"],
        ] },
      },
      {
        title: "Data limitations",
        state: "Current build",
        bullets: [
          "CWRU faults were created under controlled laboratory conditions and do not represent natural plant prevalence.",
          "The current registry covers a narrow bearing, sensor, speed, and fault domain.",
          "Fault windows are labeled for evaluation but do not establish early-warning lead time in a live asset.",
          "Public benchmark performance cannot be converted into downtime, safety, or maintenance savings.",
        ],
      },
      {
        title: "Failure taxonomy",
        state: "Design target",
        table: { headers: ["Failure", "Current control", "Remaining control"], rows: [
          ["Overlap leakage", "Contiguous splits and boundary gaps", "Publish split manifest and automated leakage assertion"],
          ["Excessive false alerts", "Provisional 0.5% validation budget", "Validate alert burden with target reviewers"],
          ["Missed fault pattern", "No production claim", "Publish false negatives and slice behavior"],
          ["Domain shift", "Public-dataset disclosure", "Shadow-test new or authorized data before pilot"],
          ["Load/speed sensitivity", "No broad generalization claim", "Evaluate and calibrate by operating condition"],
          ["Operator overtrust", "Review-support language", "Keep action human-owned and display limitations in the UI"],
        ] },
      },
      {
        title: "Monitoring and versioning",
        state: "Proposed next step",
        bullets: [
          "Log model, feature-contract, threshold, and data-source versions with every score batch.",
          "Monitor score distribution, alert rate, reviewer disposition, latency, input shift, and missing data.",
          "Require frozen replay evaluation before promotion of a new artifact.",
          "Define threshold-change authority and a rollback artifact before any limited pilot.",
        ],
      },
    ],
  },
  {
    slug: "program-plan",
    label: "DELIVERY LEADERSHIP",
    title: "AI Delivery & Launch Plan",
    summary: "Sets evidence, usability, shadow-evaluation, and human-oversight gates before a limited condition-monitoring pilot.",
    sections: [
      {
        title: "Phased delivery",
        state: "Proposed next step",
        table: { headers: ["Phase", "Scope", "Exit gate"], rows: [
          ["0 · Prototype", "Current CWRU workflow", "Implemented code and limitations inspectable"],
          ["1 · Evidence release", "Pinned evaluation and failure examples", "Reproducible manifest and held-out report published"],
          ["2 · Usability validation", "3–5 engineering-adjacent reviewers", "Task completion, confusion, and review burden documented"],
          ["3 · Shadow evaluation", "New public or authorized data", "Alerts compared with known events or expert review without action"],
          ["4 · Limited pilot", "Human-reviewed workflow only", "Ownership, monitoring, rollback, and acceptable error costs approved"],
        ] },
      },
      {
        title: "Operating ownership",
        state: "Design target",
        table: { headers: ["Decision", "Accountable role"], rows: [
          ["Acceptable false-alert burden", "Reliability workflow owner"],
          ["Model and feature contract", "ML technical owner"],
          ["Threshold change", "Reliability owner with ML review"],
          ["Alert disposition", "Reliability engineer"],
          ["Pilot continuation or rollback", "Product owner and reliability owner"],
        ] },
      },
      {
        title: "Feedback loop",
        state: "Proposed next step",
        code: "flagged window → reviewer disposition → labeled example → error analysis → frozen evaluation update → model / threshold decision",
      },
      {
        title: "Launch readiness",
        state: "Proposed next step",
        bullets: [
          "Pinned evaluation and failure card published.",
          "Target reviewer can complete the investigation task without interpreting a flag as a diagnosis.",
          "Alert and system-failure ownership are named.",
          "Input, score, latency, and disposition telemetry are available.",
          "Rollback restores the prior reliability workflow and previous model artifact.",
        ],
      },
    ],
  },
  {
    slug: "recording-guide",
    label: "DEMO RUNBOOK",
    title: "Recording Guide",
    // Private working material. Change to "public" only after a validated video URL exists.
    visibility: "private",
    summary: "A product-focused recording path covering scarce labels, leakage control, review workflow, threshold tradeoffs, and evidence boundaries.",
    sections: [
      {
        title: "Setup",
        state: "Current build",
        body: ["Run from the bearing-anomaly-detection directory. The full training path downloads approximately 50 MB of public data and creates the persisted model artifacts used by the dashboard."],
        code: "python3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npython models.py\nstreamlit run app.py",
      },
      {
        title: "60–90 second narrative",
        state: "Current build",
        table: { headers: ["Time", "Show", "Say"], rows: [
          ["0–10s", "Product title", "Reliability teams often have abundant healthy history and few labeled failures. This tool prioritizes windows for human review."],
          ["10–25s", "Windowing and split logic", "Overlapping windows are split contiguously with boundary gaps so near-duplicates do not inflate evaluation."],
          ["25–40s", "Two detector paths", "The prototype compares a five-feature Isolation Forest with a raw-waveform LSTM; complexity is not assumed to be better."],
          ["40–65s", "Bundled demo in Streamlit", "The reviewer sees flagged windows, anomaly scores, and the operating threshold rather than only a binary alarm."],
          ["65–80s", "Sensitivity slider", "Changing sensitivity makes the alert-burden tradeoff visible. The 0.5% validation budget is provisional, not a plant-approved requirement."],
          ["80–90s", "Repository and limitations", "The workflow is implemented on public bearing data; production validity and savings are not claimed."],
        ] },
      },
      {
        title: "Metric rule",
        state: "Proposed next step",
        body: ["Do not narrate the README’s model scores in the final recording until the pinned evaluation artifact is reproduced. If the dashboard displays metrics from the bundled labeled CSV, describe them only as results for that visible sample and model artifact."],
      },
    ],
  },
];
